"""
OCM-Stellar-Dynamics: Topological Resonance Archetypes
Module implementing Archetype I: Concentric Nodal Shells (Symmetrical Nested Rings).
"""

import numpy as np
from typing import Dict, List, Tuple

class ConcentricNodalShell:
    """
    Models Archetype I systems where stellar components are anchored to 
    discrete, concentric harmonic horizons defined by standing-wave metric boundaries.
    """
    
    def __init__(self, system_name: str, n_components: int, shell_radii: List[float]):
        """
        Parameters:
            system_name (str): Name of the system (e.g., 'Castor', 'Nu Scorpii').
            n_components (int): Total stellar multiplicity.
            shell_radii (List[float]): Radii of concentric harmonic shells [AU].
        """
        self.system_name = system_name
        self.n_components = n_components
        self.shell_radii = np.asfarray(shell_radii)

    def calculate_harmonic_pumping_potential(self, inner_core_mass: float, radius: float) -> float:
        """
        Calculates the metric pump potential generated by a dense inner core
        that establishes outer harmonic trapping horizons.
        
        Parameters:
            inner_core_mass (float): Combined mass of inner binary/triple core [Solar Masses].
            radius (float): Distance from primary system barycenter [AU].
            
        Returns:
            float: Effective metric trapping potential.
        """
        # Standing-wave potential profile along concentric nodal shells
        k_wave = 2.0 * np.pi / np.min(self.shell_radii)
        harmonic_potential = -(inner_core_mass / radius) * np.cos(k_wave * radius)
        return float(harmonic_potential)

    def verify_fractal_matrix_split(self, c_ii_weight: float) -> Tuple[bool, float]:
        """
        Verifies if a fractal micro-nodal matrix (c_ij) splits mass evenly 
        across nested binary pairs (e.g., Castor Aa/Ab, Ba/Bb, Ca/Cb).
        
        Parameters:
            c_ii_weight (float): Micro-nodal matrix weight coefficient.
            
        Returns:
            Tuple[bool, float]: (Is_Stable, Calculated_Symmetry_Ratio)
        """
        # Mass distribution symmetry ratio across fractal sub-nodes
        symmetry_ratio = c_ii_weight / (self.n_components / 2.0)
        is_stable = 0.15 <= symmetry_ratio <= 0.45
        return is_stable, float(symmetry_ratio)


def evaluate_castor_system() -> Dict[str, float]:
    """
    Evaluates specific OCM topological parameters for the 6-star Castor matrix.
    """
    castor_shell = ConcentricNodalShell(
        system_name="Castor",
        n_components=6,
        shell_radii=[3.0, 4.0, 1000.0]  # Aa/Ab, Ba/Bb, Ca/Cb orbits in AU
    )
    
    is_stable, ratio = castor_shell.verify_fractal_matrix_split(c_ii_weight=0.885)
    
    return {
        "system": "Castor",
        "multiplicity": 6,
        "fractal_symmetry_ratio": ratio,
        "is_topologically_stable": is_stable
    }
