"""
OCM-Stellar-Dynamics: Topological Resonance Archetypes
Module implementing Archetype I: Concentric Nodal Shells (Symmetrical Nested Rings).
Includes models for Castor, Nu Scorpii, Beta Capricorni, and Mizar.
"""

import numpy as np
from typing import Dict, List, Tuple

class ConcentricNodalShell:
    """
    Models Archetype I systems where stellar components are anchored to 
    discrete, concentric harmonic horizons defined by standing-wave metric boundaries.
    """
    
    def __init__(self, system_name: str, n_components: int, shell_radii: List[float]):
        """
        Parameters:
            system_name (str): Name of the system (e.g., 'Castor', 'Nu Scorpii').
            n_components (int): Total stellar multiplicity.
            shell_radii (List[float]): Radii of concentric harmonic shells [AU].
        """
        self.system_name = system_name
        self.n_components = n_components
        self.shell_radii = np.asfarray(shell_radii)

    def calculate_harmonic_pumping_potential(self, inner_core_mass: float, radius: float) -> float:
        """
        Calculates the metric pump potential generated by a dense inner core
        that establishes outer harmonic trapping horizons.
        
        Parameters:
            inner_core_mass (float): Combined mass of inner binary/triple core [Solar Masses].
            radius (float): Distance from primary system barycenter [AU].
            
        Returns:
            float: Effective metric trapping potential.
        """
        k_wave = 2.0 * np.pi / np.min(self.shell_radii)
        harmonic_potential = -(inner_core_mass / radius) * np.cos(k_wave * radius)
        return float(harmonic_potential)

    def verify_fractal_matrix_split(self, c_ii_weight: float) -> Tuple[bool, float]:
        """
        Verifies if a fractal micro-nodal matrix (c_ij) splits mass evenly 
        across nested binary pairs.
        
        Parameters:
            c_ii_weight (float): Micro-nodal matrix weight coefficient.
            
        Returns:
            Tuple[bool, float]: (Is_Stable, Calculated_Symmetry_Ratio)
        """
        symmetry_ratio = c_ii_weight / (self.n_components / 2.0)
        is_stable = 0.15 <= symmetry_ratio <= 0.45
        return is_stable, float(symmetry_ratio)

    def check_precession_suppression(self, mutual_inclination_deg: float, eta_m: float) -> bool:
        """
        Evaluates whether manifold viscosity (\eta_M) dampens non-linear orbital torque
        to prevent orbital plane tilting (precession).
        """
        restoration_factor = eta_m * 1e7
        dampened_inclination_drift = mutual_inclination_deg / (1.0 + restoration_factor)
        return bool(dampened_inclination_drift < 0.01)


# --- SYSTEM EVALUATORS FOR ARCHETYPE I ---

def evaluate_castor_system() -> Dict[str, object]:
    """Evaluates OCM parameters for the 6-star Castor matrix."""
    castor_shell = ConcentricNodalShell("Castor", 6, [3.0, 4.0, 1000.0])
    is_stable, ratio = castor_shell.verify_fractal_matrix_split(0.885)
    return {
        "system": "Castor",
        "multiplicity": 6,
        "fractal_symmetry_ratio": ratio,
        "is_topologically_stable": is_stable
    }

def evaluate_nu_scorpii_system() -> Dict[str, object]:
    """Evaluates metric-pumped outer standing wave trapping for Nu Scorpii (7 stars)."""
    nu_scorpii = ConcentricNodalShell("Nu Scorpii", 7, [0.005, 1.4, 47.0, 100.0])
    pump_pot = nu_scorpii.calculate_harmonic_pumping_potential(inner_core_mass=12.5, radius=47.0)
    return {
        "system": "Nu Scorpii",
        "multiplicity": 7,
        "outer_standing_wave_potential": pump_pot,
        "is_trapped_in_outer_ring": bool(pump_pot < 0)
    }

def evaluate_beta_capricorni_system() -> Dict[str, object]:
    """Evaluates harmonic shell potential for Beta Capricorni (5 stars)."""
    beta_cap = ConcentricNodalShell("Beta Capricorni", 5, [0.10, 4.5, 230.0])
    potential = beta_cap.calculate_harmonic_pumping_potential(inner_core_mass=8.2, radius=230.0)
    return {
        "system": "Beta Capricorni",
        "multiplicity": 5,
        "outer_harmonic_potential": potential,
        "is_shell_nested": bool(potential < 0)
    }

def evaluate_mizar_system() -> Dict[str, object]:
    """Evaluates plane precession suppression for the 4-star Mizar sheet."""
    mizar = ConcentricNodalShell("Mizar", 4, [0.5, 0.8, 380.0])
    is_aligned = mizar.check_precession_suppression(mutual_inclination_deg=0.5, eta_m=0.95e-7)
    return {
        "system": "Mizar",
        "multiplicity": 4,
        "is_sheet_phase_locked": is_aligned
    }
