"""
OCM-Stellar-Dynamics: Torsional Boundary Condition Engine (SM4)
Evaluates external perturbation torques against metric restoration torques:
\\oint_{\\Sigma} ( \\tau^{\\mu\\nu}_{\\text{ext}} + \\eta_M \\nabla^{[\\mu} S^{\\nu]} ) d\\Sigma = 0
"""

import numpy as np
from typing import Dict, Tuple
from src.constants import DEFAULT_ETA_M

def compute_restoration_torque(tau_external: np.ndarray, 
                               shear_tensor: np.ndarray, 
                               eta_m: float = DEFAULT_ETA_M) -> Tuple[np.ndarray, bool]:
    """
    Computes the geometric restoration torque \tau^{\mu\nu}_{M} operating across 
    the closed boundary horizon \Sigma.

    Parameters:
        tau_external (np.ndarray): Shape (3, 3) external non-axial torque tensor.
        shear_tensor (np.ndarray): Shape (3, 3) perturbation shear tensor \nabla^{[\mu} S^{\nu]}.
        eta_m (float): Localized manifold viscosity parameter.

    Returns:
        Tuple[np.ndarray, bool]: (tau_restoration, is_precession_neutralized)
    """
    # Metric restoration torque generated by localized manifold viscosity spike
    tau_restoration = - eta_m * shear_tensor
    
    # Net boundary condition flux
    net_torque = tau_external + tau_restoration
    net_magnitude = float(np.linalg.norm(net_torque))
    
    # Precession is completely suppressed if net magnitude collapses to zero
    is_precession_neutralized = net_magnitude < 1e-10
    
    return tau_restoration, is_precession_neutralized

def evaluate_inclination_time_derivative(net_torque_mag: float, 
                                          angular_momentum_mag: float) -> float:
    """
    Evaluates net mutual inclination time derivative:
    d/dt <i_jk> = 0
    """
    d_i_dt = net_torque_mag / (angular_momentum_mag + 1e-15)
    return float(d_i_dt)
